### ISSUE TITLE
pass@k for the LeetCodeContestsDataset

### ISSUE THREAD

**Issue by huangd1999** [Nan-Do/LeetCodeContestsDataset#2]
How can we evaluate the pass@k for the LeetCodeContestsDataset?
I think only calculating the CodeBLEU and BLEU is not enough.

**Comment by Nan-Do** [comment]
First of all I must say that I'm not a researcher, by this I mean that I am not familiar with what is expected in the field today to publish something.  

That said if I were to review or publish based on this dataset I wouldn't use CodeBLEU or BLEU as those are too restrictive, there are many ways to give the right solution to a problem and these tests capture, at best, how the model do at one particular solution.   

I think [human-eval](https://github.com/openai/human-eval) is widely accepted today and a better approach to evaluate a code model but that's also not particularly good to evaluate this dataset. 

Ideally, I would take out some random problems for each category of problems (easy, medium, hard) from the dataset and  prepare tests for possible solutions and time constraints. For example, tests to see if  the model can produce the brute force solution, the optimal solution in O(n^2), in O(nlogn) etc...   
And provide an analysis for the model in this way.
