### ISSUE TITLE
Outdated Dataset

### ISSUE THREAD

**Issue by anxkhn** [Nan-Do/LeetCodeContestsDataset#3]
The current dataset is quite limited and outdated.

Suggestion:
The standard questions are missing.
There are 3003 questions in Leetcode, however this dataset has 1/3th is covered.
A good resource is here github.com/walkccc/LeetCode

**Comment by Nan-Do** [comment]
I'm not sure how to answer this but to close this issue I'll clarify some points:
  - This is not a dataset about **Leetcode** but **Leetcode's contests**:
       -  Leetcode is a **private site** which charges money to serve problems (amongst other services). 
       - In contrast, the information from the contests to this day is **public** and can be used.
  - This dataset do not include **personal solutions** but tens of thousands of **validated** solutions from the best coders Leetcode has to offer.
  - This dataset has been curated to be used to train **LLMs**: 
     - The dataset has been edited and formatted accordingly.
     - The dataset includes only medium and hard questions as its intention is to **check** the ability LLMs have to **reason**. 

As a final note from those 3000 questions several hundreds are SQL, Javascript, Bash and/or questions behind the paywall so in practice this dataset covers a number closer to 50% of the programing problems.
